ARG VARIANT="3.11-bookworm"
# INFO, full list of python devcontainers available:
    # https://mcr.microsoft.com/v2/vscode/devcontainers/python/tags/list
FROM mcr.microsoft.com/vscode/devcontainers/python:${VARIANT}

ENV PATH="/home/vscode/.local/bin:${PATH}"
